SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Jogo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AmigoId] [int]  NULL,
	[Nome] [varchar](50) NOT NULL,

 CONSTRAINT [PK_Jogo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[Jogo]  WITH CHECK ADD  CONSTRAINT [FK_Jogo_Amigo] FOREIGN KEY([AmigoId])
REFERENCES [dbo].[Amigo] ([Id])
GO




